[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ezmsg"
authors = [{name = "JHU/APL", email = "hannah.gooden@jhuapl.edu"}]
dynamic = ["version", "description"]
